<a href="https://colab.research.google.com/github/18felasofa/Analisis-Deret-Waktu/blob/main/Tugas_Kelompok_UTS_Data%20Soetta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# TABULASI DATA RUMAH TANGGA + PEUBAH PENYERTA PODES
# ============================================================

import pandas as pd
import numpy as np

# ============================================================
# 1. LOKASI FILE
# ============================================================

file_rumah_tangga = r"/content/Peubah_Respon_Rumahtangga.xlsx"
file_podes = r"/content/PeubahPenyerta_Desa.xlsx"

output_file = r"D:\Kuliah\TESIS\SAE\Final\Data\data_gabungan_rumah_tangga_podes.xlsx"


# ============================================================
# 2. MEMBACA DATA
# ============================================================

df_rt = pd.read_excel(file_rumah_tangga)
df_podes = pd.read_excel(file_podes)

print("=" * 70)
print("UKURAN DATA AWAL")
print("=" * 70)

print("Data rumah tangga :", df_rt.shape)
print("Data PODES        :", df_podes.shape)


# ============================================================
# 3. MEMERIKSA VARIABEL UTAMA
# ============================================================

print("\nKolom rumah tangga:")
print(df_rt.columns.tolist())

print("\nKolom PODES:")
print(df_podes.columns.tolist())


# ============================================================
# 4. STANDARDISASI NAMA DESA DAN KECAMATAN
# ============================================================

def standardisasi_nama(x):
    """
    Standardisasi nama wilayah agar:
    - huruf kecil
    - underscore menjadi spasi
    - spasi ganda dihilangkan
    - spasi awal/akhir dihilangkan
    """

    if pd.isna(x):
        return np.nan

    x = str(x).lower().strip()
    x = x.replace("_", " ")
    x = " ".join(x.split())

    return x


df_rt["Desa_std"] = df_rt["Desa"].apply(standardisasi_nama)
df_rt["Kecamatan_std"] = df_rt["Kecamatan"].apply(standardisasi_nama)

df_podes["Desa_std"] = df_podes["Desa"].apply(standardisasi_nama)
df_podes["Kecamatan_std"] = df_podes["NAMA_KEC"].apply(standardisasi_nama)


# ============================================================
# 5. MEMBUAT KUNCI DESA + KECAMATAN
# ============================================================

df_rt["KEY_DESA"] = (
    df_rt["Kecamatan_std"] + "|" + df_rt["Desa_std"]
)

df_podes["KEY_DESA"] = (
    df_podes["Kecamatan_std"] + "|" + df_podes["Desa_std"]
)


print("\nContoh KEY_DESA rumah tangga:")
display(
    df_rt[
        ["Kecamatan", "Desa", "KEY_DESA"]
    ].head(10)
)

print("\nContoh KEY_DESA PODES:")
display(
    df_podes[
        ["NAMA_KEC", "Desa", "KEY_DESA"]
    ].head(10)
)


# ============================================================
# 6. MEMERIKSA DUPLIKASI DATA PODES
# ============================================================

duplikat_key = df_podes["KEY_DESA"].duplicated(keep=False)

print("\n" + "=" * 70)
print("PEMERIKSAAN DUPLIKASI PODES")
print("=" * 70)

print(
    "Jumlah baris PODES dengan KEY_DESA duplikat:",
    duplikat_key.sum()
)

print(
    "Jumlah KEY_DESA unik:",
    df_podes["KEY_DESA"].nunique()
)

if duplikat_key.sum() > 0:

    print("\nPERHATIAN:")
    print(
        "Masih terdapat KEY_DESA yang duplikat. "
        "Periksa data berikut:"
    )

    display(
        df_podes.loc[
            duplikat_key,
            [
                "IDDESA",
                "NAMA_KEC",
                "Desa",
                "KEY_DESA"
            ]
        ].sort_values("KEY_DESA")
    )


# ============================================================
# 7. MEMERIKSA APAKAH IDDESA UNIK
# ============================================================

print("\n" + "=" * 70)
print("PEMERIKSAAN IDDESA")
print("=" * 70)

print(
    "Jumlah IDDESA:",
    df_podes["IDDESA"].nunique()
)

print(
    "Jumlah baris PODES:",
    len(df_podes)
)

if df_podes["IDDESA"].duplicated().sum() > 0:

    print("\nPERINGATAN: IDDESA masih memiliki duplikasi.")

    display(
        df_podes[
            df_podes["IDDESA"].duplicated(keep=False)
        ].sort_values("IDDESA")
    )


# ============================================================
# 8. MEMILIH PEUBAH PENYERTA PODES
# ============================================================

# X1 sampai X15 adalah peubah penyerta
peubah_penyerta = [
    f"X{i}" for i in range(1, 16)
]

print("\nPeubah penyerta yang digunakan:")
print(peubah_penyerta)


# ============================================================
# 9. MEMBUAT DATA PODES YANG AKAN DIGABUNGKAN
# ============================================================

kolom_podes = [
    "KEY_DESA",
    "IDDESA",
    "NAMA_KEC",
    "Desa"
] + peubah_penyerta

df_podes_join = df_podes[kolom_podes].copy()


# ============================================================
# 10. MERGE DATA RUMAH TANGGA DENGAN PODES
# ============================================================

df_gabungan = pd.merge(
    df_rt,
    df_podes_join,
    on="KEY_DESA",
    how="left",
    validate="many_to_one",
    indicator=True
)


# ============================================================
# 11. HASIL MERGE
# ============================================================

print("\n" + "=" * 70)
print("HASIL PENGGABUNGAN")
print("=" * 70)

print("Jumlah rumah tangga awal :", len(df_rt))
print("Jumlah data setelah merge:", len(df_gabungan))

print("\nStatus penggabungan:")
print(
    df_gabungan["_merge"].value_counts()
)


# ============================================================
# 12. RUMAH TANGGA YANG TIDAK MENDAPAT PEUBAH PODES
# ============================================================

tidak_match = df_gabungan[
    df_gabungan["_merge"] == "left_only"
].copy()

print("\nJumlah rumah tangga yang tidak mendapatkan data PODES:")
print(len(tidak_match))


if len(tidak_match) > 0:

    print("\nDaftar desa yang tidak berhasil dicocokkan:")

    display(
        tidak_match[
            [
                "Kecamatan",
                "Desa",
                "KEY_DESA"
            ]
        ].drop_duplicates()
        .sort_values(["Kecamatan", "Desa"])
    )


# ============================================================
# 13. RUMAH TANGGA YANG BERHASIL DIGABUNGKAN
# ============================================================

match = df_gabungan[
    df_gabungan["_merge"] == "both"
].copy()

print("\nJumlah rumah tangga berhasil digabungkan:")
print(len(match))


# ============================================================
# 14. MENAMPILKAN TABULASI RUMAH TANGGA
# ============================================================

kolom_tabulasi = [
    "IDDESA",
    "Kecamatan",
    "Desa",
    "Jumlah_ART",
    "Y_perkapita"
] + peubah_penyerta

kolom_tabulasi = [
    x for x in kolom_tabulasi
    if x in df_gabungan.columns
]

print("\n" + "=" * 70)
print("TABULASI DATA RUMAH TANGGA + PODES")
print("=" * 70)

display(
    df_gabungan[
        kolom_tabulasi
    ].head(20)
)


# ============================================================
# 15. MEMERIKSA CONTEXTUAL VARIABLE
# ============================================================

print("\n" + "=" * 70)
print("PEMERIKSAAN CONTEXTUAL VARIABLES")
print("=" * 70)

for var in peubah_penyerta:

    if var in df_gabungan.columns:

        cek = (
            df_gabungan
            .groupby("KEY_DESA")[var]
            .nunique(dropna=True)
        )

        jumlah_berbeda = (cek > 1).sum()

        print(
            f"{var}: "
            f"{jumlah_berbeda} desa memiliki nilai berbeda "
            f"antar rumah tangga"
        )


# ============================================================
# 16. MEMBUAT TABULASI LEVEL DESA
# ============================================================

tabulasi_desa = (
    df_gabungan
    .groupby(
        [
            "IDDESA",
            "Kecamatan",
            "Desa"
        ],
        dropna=False
    )
    .agg(
        n_rumah_tangga=(
            "Y_perkapita",
            "count"
        ),

        mean_pengeluaran=(
            "Y_perkapita",
            "mean"
        ),

        var_pengeluaran=(
            "Y_perkapita",
            "var"
        ),

        sd_pengeluaran=(
            "Y_perkapita",
            "std"
        )
    )
    .reset_index()
)


# ============================================================
# 17. MENAMBAHKAN PEUBAH PODES LEVEL DESA
# ============================================================

contextual_desa = (
    df_podes_join
    .drop_duplicates("IDDESA")
    [
        [
            "IDDESA"
        ] + peubah_penyerta
    ]
)

tabulasi_desa = pd.merge(
    tabulasi_desa,
    contextual_desa,
    on="IDDESA",
    how="left",
    validate="one_to_one"
)


# ============================================================
# 18. MENAMPILKAN TABULASI LEVEL DESA
# ============================================================

print("\n" + "=" * 70)
print("TABULASI LEVEL DESA")
print("=" * 70)

display(
    tabulasi_desa.head(20)
)


# ============================================================
# 19. MENGHAPUS KOLOM PEMBANTU
# ============================================================

df_gabungan = df_gabungan.drop(
    columns=["_merge"],
    errors="ignore"
)


# ============================================================
# 20. MENYIMPAN HASIL KE EXCEL
# ============================================================

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    df_gabungan.to_excel(
        writer,
        sheet_name="RumahTangga_Contextual",
        index=False
    )

    tabulasi_desa.to_excel(
        writer,
        sheet_name="Tabulasi_Desa",
        index=False
    )

    df_podes_join.to_excel(
        writer,
        sheet_name="PODES_Desa",
        index=False
    )


print("\n" + "=" * 70)
print("SELESAI")
print("=" * 70)

print("File hasil:")
print(output_file)

======================================================================
UKURAN DATA AWAL
======================================================================
Data rumah tangga : (500, 169)
Data PODES        : (280, 21)

Kolom rumah tangga:
['Nama Surveyor', 'Tanggal Survey', 'Nama', 'Jenis Kelamin', 'Alamat', 'R103', 'Kecamatan', 'Desa', 'RT/RW', 'No. Telp/HP', 'Tanggal Lahir', 'Pendidikan terakhir', 'Pekerjaan', 'Lainnya...14', 'Tempat Bekerja', 'Apakah dalam satu tahun terakhir ada anggota keluarga dibawah umur 1 tahun yang meninggal?', 'Karbohidrat', 'Protein', 'SayurandanKacang', 'Buah', 'Rokok', 'Lainnya_Makanan', 'Waktu...23', 'Nilai (Rp)...24', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...25', 'Waktu...26', 'Nilai (Rp)...27', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...28', 'Waktu...29', 'Nilai (Rp)...30', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...31', 'Waktu...32', 'Nilai (Rp)...33', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...34', 'Waktu...35', 'Nilai (Rp)...36', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...37', 'Waktu...38', 'Nilai (Rp)...39', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...40', '__Selamat !__ sudah menyelesaikan 100% dari keseluruhan proses ini...41', 'Apa kegiatan Anda yang menggunakan waktu terbanyak selama 1 minggu terakhir?', 'Lainnya...43', 'Seberapa puas Anda dengan kegiatan yang menggunakan waktu terbanyak tersebut?', 'Apa bidang pekerjaan/lapangan usaha utama dari tempat Anda bekerja?', 'Apa jenis pekerjaan/usaha utama Anda?', 'Status/kedudukan dalam pekerjaan/usaha utama', 'Apakah Anda memiliki pekerjaan/usaha tambahan selain pekerjaan/usaha utama?', 'a. Apakah pekerjaan/usaha Anda sesuai dengan bidang keahlian/keterampilan?', 'b. Apakah pekerjaan/usaha Anda sesuai dengan minat/keinginan?', 'c. Apakah penghasilan dari pekerjaan/ usaha Anda sesuai dengan jerih payah, baik dari sisi waktu maupun tenaga yang digunakan?', 'd. Apakah situasi/kondisi di tempat kerja/ usaha Anda nyaman/menyenangkan?', 'e. Apakah kondisi di tempat kerja/usaha Anda aman/terlindungi dari kecelakaan kerja?', 'f. Apakah pekerjaan/usaha Anda mempunyai kepastian keberlangsungannya?', 'g. Apakah tempat kerja/usaha Anda mudah dicapai?', 'Berapa rata-rata upah/gaji/pendapatan per bulan Anda dari seluruh pekerjaan/usaha dalam 1 tahun terakhir?', 'Seberapa puas Anda dengan pekerjaan/usaha?', 'Seberapa sering Anda mengalami keluhan kesehatan (seperti panas, batuk, pilek, nafas sesak, dll) selama 6 bulan terakhir?', 'Seberapa sering menyebabkan terganggunya kegiatan sehari-hari Anda selama 6 bulan terakhir?', 'Apakah Anda mengidap penyakit kronis/menahun yang telah dinyatakan oleh dokter?', 'Apa nama penyakit kronis/menahun Anda?', 'Apakah selama 6 bulan terakhir, Anda melakukan rawat inap?', 'Apakah selama 6 bulan terakhir, Anda melakukan rawat jalan?', 'Seberapa puas Anda dengan kesehatan?', 'Jika tidak melakukan rawat inap dan rawat jalan, alasan utamanya :', 'Lainnya...66', 'Seberapa sering Anda bertemu/berbicara/berkomunikasi dengan anggota keluarga selama 1 bulan terakhir?', 'Seberapa sering Anda melakukan kegiatan bersama keluarga (seperti: rekreasi, makan malam, nonton televisi, dan sebagainya) selama 1 bulan terakhir?', 'Seberapa sering Anda bertengkar/tidak akur dengan anggota keluarga selama 1 bulan terakhir?', 'Apakah Anda merasa dihormati oleh seluruh anggota keluarga selama 1 bulan terakhir?', 'Berobat bila sakit', 'Memilih pekerjaan?', 'Memilih teman/kelompok/pergaulan?', 'Menentukan pendidikan?', 'Seberapa puas Anda dengan keharmonisan keluarga?', 'Berapa jam waktu yang biasanya Anda gunakan untuk bekerja, mengurus rumah tangga, atau sekolah dalam 1 minggu?', 'Berapa jam waktu luang yang biasanya Anda miliki dalam 1 minggu?', 'Nonton televisi/video/bioskop/pertunjukan, mendengarkan musik, karaoke dan sebagainya?', 'Membaca koran, majalah, buku, atau sejenisnya?', 'Berolahraga?', 'Bersosialisasi dengan tetangga?', 'Rekreasi, mengerjakan hobi, atau sejenisnya?', 'Bersama siapa waktu luang tersebut paling banyak Anda gunakan?', 'Seberapa puas Anda dengan ketersediaan waktu luang?', 'Apakah Anda mengetahui nama-nama tetangga di lingkungan sekitar tempat tinggal?', 'Seberapa sering Anda bersosialisasi/bergaul/ bertegur sapa dengan tetangga selama 1 bulan terakhir?', 'Seberapa bersedia Anda untuk membantu orang lain yang butuh pertolongan keuangan di lingkungan sekitar tempat tinggal?', 'Seberapa puas Anda dengan hubungan sosial terhadap warga di lingkungan sekitar tempat tinggal?', 'Seberapa puas Anda dengan keadaan lingkungan?', 'Seberapa puas Anda dengan kondisi keamanan?', 'Apa status penguasaan bangunan tempat tinggal yang Anda tempati?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Kendaraan bermotor?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Komputer/Laptop/Tablet?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Peralatan Audio/Video (TV, DVD/VCD/ MP4/MP3, radio/cassette)?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Alat Komunikasi (Telepon, HP)?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Tidak ada', 'Seberapa puas Anda dengan rumah dan fasilitas rumah?', 'Seberapa senang/riang/gembira Saudara/i dalam menjalani kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak gembira, 10 = sangat gembira]', 'Seberapa khawatir/cemas Saudara/i dalam menjalani kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak cemas, 10 = sangat cemas]', 'Seberapa tertekan Saudara/i dalam menghadapi masalah di kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak tertekan, 10 = sangat tertekan]', 'Seberapa mampu Saudara/i menentukan keputusan bagi diri sendiri? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa mampu Saudara/i menciptakan kondisi yang nyaman bagi diri sendiri? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa konsisten Saudara/i dalam berupaya mengembangkan potensi diri (meningkatkan pengetahuan, keterampilan, dsb)? [skala 1 - 10, 1 = sangat kurang, 10 = sangat baik]', 'Seberapa bermanfaat Saudara/i bagi orang lain? [skala 1 - 10, 1 = sangat kurang, 10 = sangat bermanfaat]', 'Seberapa optimis Saudara/i dengan masa depan? [skala 1 - 10, 1 = sangat tidak optimis, 10 = sangat optimis]', 'Seberapa mampu Saudara/i menerima apapun kondisi yang dialami? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa bahagia Saudara/i dengan kehidupan yang dijalani saat ini secara keseluruhan?', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa arsitektur:', 'Alamat (Kecamatan)...110', 'Jumlah Pekerja...111', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di desain interior/produk:', 'Alamat (Kecamatan)...113', 'Jumlah Pekerja...114', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di biro iklan:', 'Alamat (Kecamatan)...116', 'Jumlah Pekerja...117', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa animasi video:', 'Alamat (Kecamatan)...119', 'Jumlah Pekerja...120', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa fotografi:', 'Alamat (Kecamatan)...122', 'Jumlah Pekerja...123', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di kerajinan tangan/kayu:', 'Alamat (Kecamatan)...125', 'Jumlah Pekerja...126', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di sekolah musik:', 'Alamat (Kecamatan)...128', 'Jumlah Pekerja...129', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di industri RT untuk fashion:', 'Alamat (Kecamatan)...131', 'Jumlah Pekerja...132', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa IT bidang game development:', 'Alamat (Kecamatan)...134', 'Jumlah Pekerja...135', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa penerbitan cetak/elektronik:', 'Alamat (Kecamatan)...137', 'Jumlah Pekerja...138', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa televisi dan radio:', 'Alamat (Kecamatan)...140', 'Jumlah Pekerja...141', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa seni rupa:', 'Alamat (Kecamatan)...143', 'Jumlah Pekerja...144', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa pertunjukan:', 'Alamat (Kecamatan)...146', 'Jumlah Pekerja...147', '__Selamat !__ sudah menyelesaikan 100% dari keseluruhan proses ini...148', 'Status dalam keluarga', 'Apa Anda memiliki sertifikat keterampilan', 'Mengikuti kegiatan pelatihan, kursus, penyuluhan, dan sejenisnya?', 'Membaca media cetak atau elektronik (membaca koran/majalah/buku/ dokumen elektronik/media lainnya, menonton televisi, mendengarkan radio dan sebagainya)?', 'Mendapatkan atau membaca informasi/pengetahuan secara mandiri melalui internet?', 'Seberapa puas Anda dengan pendidikan dan keterampilan yang dimiliki? Sangat tidak puas (1)-Sangat puas (10)', 'Apakah Anda bekerja/berusaha atau sementara tidak bekerja selama 1 minggu terakhir?', '_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', '_index', 'Jumlah_ART', 'Total_Makanan_Mingguan', 'Total_Makanan_Bulanan', 'Y_perkapita']

Kolom PODES:
['IDDESA', 'R103', 'R104', 'NAMA_KEC', 'Desa', 'total_keluarga', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15']

Contoh KEY_DESA rumah tangga:

      Kecamatan                   Desa                            KEY_DESA
0      Cileunyi         Cileunyi Kulon             cileunyi|cileunyi kulon
1  Kutawaringin  Jatisari_Kutawaringin  kutawaringin|jatisari kutawaringin
2      Cileunyi         Cileunyi Kulon             cileunyi|cileunyi kulon
3      Cileunyi         Cileunyi_Kulon             cileunyi|cileunyi kulon
4     Margahayu              Sukamenak                 margahayu|sukamenak
5  Kutawaringin  Jatisari_Kutawaringin  kutawaringin|jatisari kutawaringin
6      Cileunyi         Cileunyi_Kulon             cileunyi|cileunyi kulon
7      Cileunyi         Cileunyi Kulon             cileunyi|cileunyi kulon
8  Kutawaringin  Jatisari_Kutawaringin  kutawaringin|jatisari kutawaringin
9     Margahayu              Sukamenak                 margahayu|sukamenak

Contoh KEY_DESA PODES:

    NAMA_KEC          Desa              KEY_DESA
0    Ciwidey     Panundaan     ciwidey|panundaan
1    Ciwidey       Ciwidey       ciwidey|ciwidey
2    Ciwidey    Panyocokan    ciwidey|panyocokan
3    Ciwidey  Lebakmuncang  ciwidey|lebakmuncang
4    Ciwidey      Rawabogo      ciwidey|rawabogo
5    Ciwidey     Nengkelan     ciwidey|nengkelan
6    Ciwidey    Sukawening    ciwidey|sukawening
7  Rancabali       Cipelah     rancabali|cipelah
8  Rancabali     Sukaresmi   rancabali|sukaresmi
9  Rancabali     Indragiri   rancabali|indragiri

======================================================================
PEMERIKSAAN DUPLIKASI PODES
======================================================================
Jumlah baris PODES dengan KEY_DESA duplikat: 0
Jumlah KEY_DESA unik: 280

======================================================================
PEMERIKSAAN IDDESA
======================================================================
Jumlah IDDESA: 280
Jumlah baris PODES: 280

Peubah penyerta yang digunakan:
['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15']

======================================================================
HASIL PENGGABUNGAN
======================================================================
Jumlah rumah tangga awal : 500
Jumlah data setelah merge: 500

Status penggabungan:
_merge
both          470
left_only      30
right_only      0
Name: count, dtype: int64

Jumlah rumah tangga yang tidak mendapatkan data PODES:
30

Daftar desa yang tidak berhasil dicocokkan:

KeyError: "['Desa'] not in index"

In [ ]:
# ============================================================
# 1. IMPORT PACKAGE
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path


# ============================================================
# 2. LOKASI FILE
# ============================================================

file_rumah_tangga = r"/content/Peubah_Respon_Rumahtangga.xlsx"
file_podes = r"/content/PeubahPenyerta_Desa.xlsx"

output_file = r"D:\Kuliah\TESIS\SAE\Final\Data\data_gabungan_rumah_tangga_podes.xlsx"


# ============================================================
# 3. MEMBACA DATA
# ============================================================

df_rt = pd.read_excel(file_rumah_tangga)
df_podes = pd.read_excel(file_podes)

print("Ukuran data rumah tangga :", df_rt.shape)
print("Ukuran data PODES       :", df_podes.shape)

print("\nKolom data rumah tangga:")
print(df_rt.columns.tolist())

print("\nKolom data PODES:")
print(df_podes.columns.tolist())

Ukuran data rumah tangga : (500, 169)
Ukuran data PODES       : (280, 21)

Kolom data rumah tangga:
['Nama Surveyor', 'Tanggal Survey', 'Nama', 'Jenis Kelamin', 'Alamat', 'R103', 'Kecamatan', 'Desa', 'RT/RW', 'No. Telp/HP', 'Tanggal Lahir', 'Pendidikan terakhir', 'Pekerjaan', 'Lainnya...14', 'Tempat Bekerja', 'Apakah dalam satu tahun terakhir ada anggota keluarga dibawah umur 1 tahun yang meninggal?', 'Karbohidrat', 'Protein', 'SayurandanKacang', 'Buah', 'Rokok', 'Lainnya_Makanan', 'Waktu...23', 'Nilai (Rp)...24', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...25', 'Waktu...26', 'Nilai (Rp)...27', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...28', 'Waktu...29', 'Nilai (Rp)...30', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...31', 'Waktu...32', 'Nilai (Rp)...33', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...34', 'Waktu...35', 'Nilai (Rp)...36', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...37', 'Waktu...38', 'Nilai (Rp)...39', 'Frekuensi dalam setahun (untuk pilihan waktu bulanan)...40', '__Selamat !__ sudah menyelesaikan 100% dari keseluruhan proses ini...41', 'Apa kegiatan Anda yang menggunakan waktu terbanyak selama 1 minggu terakhir?', 'Lainnya...43', 'Seberapa puas Anda dengan kegiatan yang menggunakan waktu terbanyak tersebut?', 'Apa bidang pekerjaan/lapangan usaha utama dari tempat Anda bekerja?', 'Apa jenis pekerjaan/usaha utama Anda?', 'Status/kedudukan dalam pekerjaan/usaha utama', 'Apakah Anda memiliki pekerjaan/usaha tambahan selain pekerjaan/usaha utama?', 'a. Apakah pekerjaan/usaha Anda sesuai dengan bidang keahlian/keterampilan?', 'b. Apakah pekerjaan/usaha Anda sesuai dengan minat/keinginan?', 'c. Apakah penghasilan dari pekerjaan/ usaha Anda sesuai dengan jerih payah, baik dari sisi waktu maupun tenaga yang digunakan?', 'd. Apakah situasi/kondisi di tempat kerja/ usaha Anda nyaman/menyenangkan?', 'e. Apakah kondisi di tempat kerja/usaha Anda aman/terlindungi dari kecelakaan kerja?', 'f. Apakah pekerjaan/usaha Anda mempunyai kepastian keberlangsungannya?', 'g. Apakah tempat kerja/usaha Anda mudah dicapai?', 'Berapa rata-rata upah/gaji/pendapatan per bulan Anda dari seluruh pekerjaan/usaha dalam 1 tahun terakhir?', 'Seberapa puas Anda dengan pekerjaan/usaha?', 'Seberapa sering Anda mengalami keluhan kesehatan (seperti panas, batuk, pilek, nafas sesak, dll) selama 6 bulan terakhir?', 'Seberapa sering menyebabkan terganggunya kegiatan sehari-hari Anda selama 6 bulan terakhir?', 'Apakah Anda mengidap penyakit kronis/menahun yang telah dinyatakan oleh dokter?', 'Apa nama penyakit kronis/menahun Anda?', 'Apakah selama 6 bulan terakhir, Anda melakukan rawat inap?', 'Apakah selama 6 bulan terakhir, Anda melakukan rawat jalan?', 'Seberapa puas Anda dengan kesehatan?', 'Jika tidak melakukan rawat inap dan rawat jalan, alasan utamanya :', 'Lainnya...66', 'Seberapa sering Anda bertemu/berbicara/berkomunikasi dengan anggota keluarga selama 1 bulan terakhir?', 'Seberapa sering Anda melakukan kegiatan bersama keluarga (seperti: rekreasi, makan malam, nonton televisi, dan sebagainya) selama 1 bulan terakhir?', 'Seberapa sering Anda bertengkar/tidak akur dengan anggota keluarga selama 1 bulan terakhir?', 'Apakah Anda merasa dihormati oleh seluruh anggota keluarga selama 1 bulan terakhir?', 'Berobat bila sakit', 'Memilih pekerjaan?', 'Memilih teman/kelompok/pergaulan?', 'Menentukan pendidikan?', 'Seberapa puas Anda dengan keharmonisan keluarga?', 'Berapa jam waktu yang biasanya Anda gunakan untuk bekerja, mengurus rumah tangga, atau sekolah dalam 1 minggu?', 'Berapa jam waktu luang yang biasanya Anda miliki dalam 1 minggu?', 'Nonton televisi/video/bioskop/pertunjukan, mendengarkan musik, karaoke dan sebagainya?', 'Membaca koran, majalah, buku, atau sejenisnya?', 'Berolahraga?', 'Bersosialisasi dengan tetangga?', 'Rekreasi, mengerjakan hobi, atau sejenisnya?', 'Bersama siapa waktu luang tersebut paling banyak Anda gunakan?', 'Seberapa puas Anda dengan ketersediaan waktu luang?', 'Apakah Anda mengetahui nama-nama tetangga di lingkungan sekitar tempat tinggal?', 'Seberapa sering Anda bersosialisasi/bergaul/ bertegur sapa dengan tetangga selama 1 bulan terakhir?', 'Seberapa bersedia Anda untuk membantu orang lain yang butuh pertolongan keuangan di lingkungan sekitar tempat tinggal?', 'Seberapa puas Anda dengan hubungan sosial terhadap warga di lingkungan sekitar tempat tinggal?', 'Seberapa puas Anda dengan keadaan lingkungan?', 'Seberapa puas Anda dengan kondisi keamanan?', 'Apa status penguasaan bangunan tempat tinggal yang Anda tempati?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Kendaraan bermotor?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Komputer/Laptop/Tablet?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Peralatan Audio/Video (TV, DVD/VCD/ MP4/MP3, radio/cassette)?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Alat Komunikasi (Telepon, HP)?', 'Apakah di rumah Anda tersedia barang-barang penunjang kehidupan yang nyaman (masih digunakan/ berfungsi) berikut ini:/Tidak ada', 'Seberapa puas Anda dengan rumah dan fasilitas rumah?', 'Seberapa senang/riang/gembira Saudara/i dalam menjalani kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak gembira, 10 = sangat gembira]', 'Seberapa khawatir/cemas Saudara/i dalam menjalani kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak cemas, 10 = sangat cemas]', 'Seberapa tertekan Saudara/i dalam menghadapi masalah di kehidupan sehari-hari? [skala 1 - 10, 1 = sangat tidak tertekan, 10 = sangat tertekan]', 'Seberapa mampu Saudara/i menentukan keputusan bagi diri sendiri? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa mampu Saudara/i menciptakan kondisi yang nyaman bagi diri sendiri? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa konsisten Saudara/i dalam berupaya mengembangkan potensi diri (meningkatkan pengetahuan, keterampilan, dsb)? [skala 1 - 10, 1 = sangat kurang, 10 = sangat baik]', 'Seberapa bermanfaat Saudara/i bagi orang lain? [skala 1 - 10, 1 = sangat kurang, 10 = sangat bermanfaat]', 'Seberapa optimis Saudara/i dengan masa depan? [skala 1 - 10, 1 = sangat tidak optimis, 10 = sangat optimis]', 'Seberapa mampu Saudara/i menerima apapun kondisi yang dialami? [skala 1 - 10, 1 = sangat tidak mampu, 10 = sangat mampu]', 'Seberapa bahagia Saudara/i dengan kehidupan yang dijalani saat ini secara keseluruhan?', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa arsitektur:', 'Alamat (Kecamatan)...110', 'Jumlah Pekerja...111', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di desain interior/produk:', 'Alamat (Kecamatan)...113', 'Jumlah Pekerja...114', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di biro iklan:', 'Alamat (Kecamatan)...116', 'Jumlah Pekerja...117', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa animasi video:', 'Alamat (Kecamatan)...119', 'Jumlah Pekerja...120', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa fotografi:', 'Alamat (Kecamatan)...122', 'Jumlah Pekerja...123', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di kerajinan tangan/kayu:', 'Alamat (Kecamatan)...125', 'Jumlah Pekerja...126', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di sekolah musik:', 'Alamat (Kecamatan)...128', 'Jumlah Pekerja...129', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di industri RT untuk fashion:', 'Alamat (Kecamatan)...131', 'Jumlah Pekerja...132', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa IT bidang game development:', 'Alamat (Kecamatan)...134', 'Jumlah Pekerja...135', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa penerbitan cetak/elektronik:', 'Alamat (Kecamatan)...137', 'Jumlah Pekerja...138', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa televisi dan radio:', 'Alamat (Kecamatan)...140', 'Jumlah Pekerja...141', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa seni rupa:', 'Alamat (Kecamatan)...143', 'Jumlah Pekerja...144', 'Apakah Bapak/Ibu atau Anggota keluarga bekerja di jasa pertunjukan:', 'Alamat (Kecamatan)...146', 'Jumlah Pekerja...147', '__Selamat !__ sudah menyelesaikan 100% dari keseluruhan proses ini...148', 'Status dalam keluarga', 'Apa Anda memiliki sertifikat keterampilan', 'Mengikuti kegiatan pelatihan, kursus, penyuluhan, dan sejenisnya?', 'Membaca media cetak atau elektronik (membaca koran/majalah/buku/ dokumen elektronik/media lainnya, menonton televisi, mendengarkan radio dan sebagainya)?', 'Mendapatkan atau membaca informasi/pengetahuan secara mandiri melalui internet?', 'Seberapa puas Anda dengan pendidikan dan keterampilan yang dimiliki? Sangat tidak puas (1)-Sangat puas (10)', 'Apakah Anda bekerja/berusaha atau sementara tidak bekerja selama 1 minggu terakhir?', '_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', '_index', 'Jumlah_ART', 'Total_Makanan_Mingguan', 'Total_Makanan_Bulanan', 'Y_perkapita']

Kolom data PODES:
['IDDESA', 'R103', 'R104', 'NAMA_KEC', 'Desa', 'total_keluarga', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15']

In [ ]:
# Melihat beberapa baris pertama
display(df_rt.head())
display(df_podes.head())

,Nama Surveyor,Tanggal Survey,Nama,Jenis Kelamin,Alamat,R103,Kecamatan,Desa,RT/RW,No. Telp/HP,...,_notes,_status,_submitted_by,__version__,_tags,_index,Jumlah_ART,Total_Makanan_Mingguan,Total_Makanan_Bulanan,Y_perkapita
0,Fajryanti Kusuma Wardani,2023-07-10,Ayi Karmini,Perempuan,Jl Ciburial Kampung Negasari,290,Cileunyi,Cileunyi Kulon,01/20,NaN,...,NaN,submitted_via_web,NaN,vGKRqTe5yzPTRssR7MCCZV,NaN,1,6,278500,1.206833e+06,201138.888889
1,Khairani Cahyoja Utami,2023-07-10,Anrohana,Perempuan,Gang Babakan Cipedung No. 58,191,Kutawaringin,Jatisari_Kutawaringin,01/01,NaN,...,NaN,submitted_via_web,NaN,vGKRqTe5yzPTRssR7MCCZV,NaN,2,3,480000,2.080000e+06,693333.333333
2,Fajryanti Kusuma Wardani,2023-07-10,Elis,Perempuan,Jl Neglasari 3,290,Cileunyi,Cileunyi Kulon,01/20,NaN,...,NaN,submitted_via_web,NaN,vGKRqTe5yzPTRssR7MCCZV,NaN,3,4,333000,1.443000e+06,360750.000000
3,Fajryanti Kusuma Wardani,2023-07-10,Ghozali,NaN,Kp Neglasari,290,Cileunyi,Cileunyi_Kulon,1/20,NaN,...,NaN,submitted_via_web,NaN,v9Dpbr96qGh64DHgkRgxYi,NaN,4,5,1015000,4.398333e+06,879666.666667
4,Febrina Nurhijah,2023-07-09,Cucu Nurhayati,Perempuan,Jalan Sumintapura,260,Margahayu,Sukamenak,05/10,089688618697,...,NaN,submitted_via_web,NaN,vGKRqTe5yzPTRssR7MCCZV,NaN,5,3,210000,9.100000e+05,303333.333333

,IDDESA,R103,R104,NAMA_KEC,Desa,total_keluarga,X1,X2,X3,X4,...,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15
0,3204010001,10,1,Ciwidey,Panundaan,4453,100.0,0.000000,0.0,0.011228,...,0.000449,0.011453,0.002470,0.000000,0.001123,0.000000,0.000674,0.034808,0.000000,0.000000
1,3204010002,10,2,Ciwidey,Ciwidey,4825,100.0,0.414508,0.0,0.016580,...,0.001658,0.064663,0.001451,0.000207,0.003523,0.000622,0.000415,0.041244,0.000622,0.000622
2,3204010003,10,3,Ciwidey,Panyocokan,4891,100.0,0.000000,0.0,0.013085,...,0.000204,0.023104,0.000000,0.000000,0.002249,0.000000,0.000000,0.043345,0.000000,0.000204
3,3204010004,10,4,Ciwidey,Lebakmuncang,5882,100.0,0.000000,0.0,0.010031,...,0.000170,0.010371,0.001360,0.000000,0.001190,0.000000,0.000000,0.005100,0.000000,0.000170
4,3204010005,10,5,Ciwidey,Rawabogo,2280,100.0,0.000000,0.0,0.010965,...,0.000000,0.037281,0.000000,0.000000,0.003070,0.000000,0.000000,0.003947,0.000000,0.000439

In [ ]:
# Cek tipe data Desa
print("Tipe Desa rumah tangga :", df_rt["Desa"].dtype)
print("Tipe Desa PODES        :", df_podes["Desa"].dtype)

Tipe Desa rumah tangga : object
Tipe Desa PODES        : object

In [ ]:
df_rt["Desa"] = (
    df_rt["Desa"]
    .astype(str)
    .str.strip()
)

df_podes["Desa"] = (
    df_podes["Desa"]
    .astype(str)
    .str.strip()
)

In [ ]:
duplikat_podes = (
    df_podes["Desa"]
    .duplicated(keep=False)
)

print("Jumlah baris PODES yang memiliki Desa duplikat:",
      duplikat_podes.sum())

display(
    df_podes.loc[duplikat_podes]
    .sort_values("Desa")
)

print("\nMenampilkan semua kolom untuk baris dengan Desa duplikat:")
with pd.option_context('display.max_columns', None):
    display(
        df_podes.loc[duplikat_podes]
        .sort_values("Desa")
    )

Jumlah baris PODES yang memiliki Desa duplikat: 50

,IDDESA,R103,R104,NAMA_KEC,Desa,total_keluarga,X1,X2,X3,X4,...,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15
143,3204120011,120,11,Majalaya,Bojong,6421,100.000000,0.000000,0.000000,0.036131,...,0.000311,0.018377,0.000000,0.000000,0.000779,0.000000,0.000000,0.022894,0.000000,0.000156
112,3204101002,101,2,Nagreg,Bojong,2147,100.000000,0.000000,0.000000,0.050769,...,0.000000,0.027946,0.000000,0.000000,0.001863,0.000000,0.000000,0.018631,0.000000,0.000000
130,3204110012,110,12,Rancaekek,Cangkuang,4712,100.000000,0.000000,0.000000,0.000637,...,0.000000,0.009975,0.000000,0.000000,0.000637,0.000000,0.000000,0.067912,0.000212,0.000000
200,3204161006,161,6,Cangkuang,Cangkuang,3158,100.000000,7.504750,0.000000,0.045915,...,0.000633,0.066498,0.000317,0.000000,0.000950,0.000317,0.000317,0.079481,0.000317,0.000317
17,3204020006,20,6,Pasirjambu,Cibodas,2929,100.000000,0.000000,0.000000,0.006145,...,0.000341,0.005804,0.000000,0.000000,0.004097,0.000000,0.000000,0.020143,0.000000,0.000341
231,3204191007,191,7,Kutawaringin,Cibodas,2628,100.000000,0.000000,0.000000,0.008371,...,0.000000,0.009513,0.000000,0.000000,0.001903,0.000381,0.000000,0.019026,0.000000,0.000000
146,3204121003,121,3,Solokan jeruk,Cibodas,3781,100.000000,3.464692,0.000000,0.004761,...,0.000000,0.030944,0.000000,0.000000,0.003438,0.000000,0.000000,0.075112,0.000000,0.002116
152,3204130002,130,2,Ciparay,Cikoneng,2025,100.000000,0.000000,0.000000,0.025679,...,0.001975,0.010864,0.000494,0.000000,0.004938,0.000000,0.000000,0.172840,0.000000,0.000000
21,3204020010,20,10,Pasirjambu,Cikoneng,2108,100.000000,0.000000,0.000000,0.120493,...,0.000000,0.008065,0.000000,0.000000,0.005218,0.000000,0.000000,0.067837,0.000000,0.000000
232,3204191008,191,8,Kutawaringin,Jatisari,4024,100.000000,0.000000,0.000000,0.023111,...,0.000000,0.004970,0.000000,0.000000,0.001988,0.000000,0.000249,0.013419,0.000000,0.000000
195,3204161001,161,1,Cangkuang,Jatisari,2372,100.000000,0.000000,0.000000,0.039207,...,0.000422,0.017285,0.000000,0.000000,0.003794,0.000000,0.000422,0.065346,0.000000,0.000000
233,3204191009,191,9,Kutawaringin,Jelegong,5338,100.000000,0.000000,0.000000,0.002623,...,0.000375,0.014238,0.000000,0.000187,0.001124,0.000187,0.000187,0.049831,0.000000,0.000187
124,3204110006,110,6,Rancaekek,Jelegong,8712,100.000000,0.000000,0.000000,0.004936,...,0.000918,0.004591,0.000000,0.000000,0.002066,0.000000,0.000230,0.149219,0.000230,0.000115
240,3204250005,250,5,Margaasih,Margaasih,8469,100.000000,0.000000,0.000000,0.026095,...,0.000945,0.024914,0.000000,0.000118,0.001771,0.000590,0.000354,0.030110,0.000472,0.000118
101,3204100003,100,3,Cicalengka,Margaasih,2894,100.000000,2.142364,0.000000,0.017968,...,0.000000,0.005529,0.000000,0.000000,0.003110,0.000346,0.000000,0.060124,0.000000,0.000000
13,3204020002,20,2,Pasirjambu,Margamulya,2944,99.966033,0.169837,0.000000,0.012228,...,0.000000,0.029891,0.000000,0.000000,0.002378,0.000000,0.000340,0.028872,0.000000,0.000000
42,3204040011,40,11,Pangalengan,Margamulya,5936,100.000000,0.000000,0.488544,0.011287,...,0.000337,0.006739,0.000337,0.000000,0.001853,0.000000,0.000337,0.047507,0.000168,0.000000
62,3204060010,60,10,Pacet,Mekarjaya,2437,100.000000,0.000000,0.287238,0.038572,...,0.000410,0.029955,0.000000,0.000000,0.004103,0.000000,0.000000,0.046368,0.000000,0.000000
184,3204160001,160,1,Banjaran,Mekarjaya,3551,100.000000,2.027598,0.000000,0.038581,...,0.000000,0.018586,0.000000,0.000000,0.001690,0.000000,0.000000,0.070684,0.000000,0.000000
175,3204150003,150,3,Arjasari,Mekarjaya,2341,100.000000,0.000000,0.000000,0.019650,...,0.000000,0.000000,0.000000,0.000000,0.002563,0.000427,0.000000,0.047843,0.000000,0.004699
92,3204090003,90,3,Cikancung,Mekarlaksana,2243,100.000000,0.000000,0.000000,0.002675,...,0.000000,0.015604,0.000000,0.000000,0.002229,0.000446,0.000000,0.019171,0.000000,0.000000
163,3204130013,130,13,Ciparay,Mekarlaksana,3147,100.000000,0.000000,0.000000,0.010804,...,0.000000,0.003495,0.000000,0.000000,0.003495,0.000000,0.000000,0.080394,0.000000,0.000000
23,3204030002,30,2,Cimaung,Mekarsari,2695,100.000000,0.000000,0.000000,0.016698,...,0.000000,0.025232,0.000000,0.000000,0.001855,0.000000,0.000000,0.017440,0.000000,0.000000
156,3204130006,130,6,Ciparay,Mekarsari,3932,100.000000,0.508647,0.000000,0.019329,...,0.000254,0.009664,0.000000,0.000000,0.003815,0.000000,0.000000,0.071719,0.000000,0.000000
16,3204020005,20,5,Pasirjambu,Mekarsari,2127,100.000000,0.000000,0.000000,0.004701,...,0.000470,0.005172,0.002351,0.000000,0.002351,0.000470,0.000000,0.019276,0.000000,0.000470
63,3204060011,60,11,Pacet,Mekarsari,2488,100.000000,0.000000,0.000000,0.124598,...,0.000000,0.005627,0.000000,0.000000,0.005225,0.000000,0.000000,0.069936,0.000000,0.000000
196,3204161002,161,2,Cangkuang,Nagrak,4563,100.000000,3.243480,0.000000,0.039229,...,0.000438,0.031339,0.000000,0.000000,0.002630,0.000438,0.000000,0.054789,0.000000,0.000000
57,3204060005,60,5,Pacet,Nagrak,3825,100.000000,0.000000,0.000000,0.013856,...,0.000000,0.022222,0.000000,0.000000,0.004183,0.000000,0.000000,0.104052,0.000000,0.000261
188,3204160005,160,5,Banjaran,Neglasari,3157,100.000000,0.633513,0.253405,0.023440,...,0.000000,0.017738,0.000000,0.000000,0.001267,0.000000,0.000317,0.048464,0.000000,0.000000
133,3204120001,120,1,Majalaya,Neglasari,3258,100.000000,0.000000,0.000000,0.003069,...,0.000000,0.014119,0.000000,0.000000,0.003069,0.000000,0.000000,0.095764,0.000000,0.000000
66,3204070001,70,1,Ibun,Neglasari,1665,100.000000,0.000000,0.000000,0.010210,...,0.000000,0.003604,0.000000,0.000000,0.003604,0.000000,0.000000,0.036637,0.000000,0.000000
227,3204191003,191,3,Kutawaringin,Padasuka,3335,100.000000,0.000000,0.000000,0.092354,...,0.000300,0.008996,0.000000,0.000000,0.000900,0.000000,0.000300,0.004498,0.000000,0.000300
272,3204310002,310,2,Cimenyan,Padasuka,6963,100.000000,0.818613,0.000000,0.006032,...,0.000431,0.015798,0.000000,0.000000,0.002154,0.000000,0.000287,0.018814,0.000000,0.000000
60,3204060008,60,8,Pacet,Pangauban,3922,100.000000,0.000000,0.000000,0.007394,...,0.000000,0.009434,0.000000,0.000000,0.004080,0.000000,0.000000,0.031362,0.000000,0.000000
211,3204180007,180,7,Katapang,Pangauban,5493,100.000000,0.000000,0.182050,0.010923,...,0.001820,0.046969,0.000182,0.000000,0.002913,0.000728,0.000910,0.090661,0.000728,0.000000
30,3204030009,30,9,Cimaung,Sukamaju,2814,100.000000,0.000000,0.000000,0.005686,...,0.000000,0.011016,0.000000,0.000000,0.001777,0.000000,0.000355,0.008173,0.000000,0.000000
139,3204120007,120,7,Majalaya,Sukamaju,5170,100.000000,0.773694,0.000000,0.002901,...,0.000193,0.037137,0.000000,0.000000,0.002708,0.000193,0.000193,0.066344,0.000193,0.000000
119,3204110001,110,1,Rancaekek,Sukamanah,2558,100.000000,0.000000,0.000000,0.011337,...,0.001173,0.010164,0.000000,0.000000,0.002737,0.000000,0.000000,0.101642,0.000000,0.000782
39,3204040008,40,8,Pangalengan,Sukamanah,5673,100.000000,0.000000,0.000000,0.014983,...,0.000529,0.025912,0.000705,0.000176,0.002292,0.000353,0.000176,0.037723,0.000000,0.000000
83,3204080006,80,6,Paseh,Sukamanah,3781,100.000000,0.000000,0.000000,0.017191,...,0.001322,0.064004,0.000000,0.000000,0.003174,0.000264,0.000793,0.017456,0.000000,0.000000
136,3204120004,120,4,Majalaya,Sukamukti,4580,100.000000,0.000000,0.000000,0.007642,...,0.000437,0.025764,0.000000,0.000000,0.001528,0.000000,0.000655,0.011572,0.000000,0.000218
214,3204180010,180,10,Katapang,Sukamukti,6114,100.000000,0.000000,0.000000,0.012594,...,0.000654,0.015538,0.000000,0.000000,0.001472,0.000000,0.000000,0.030095,0.000000,0.000000
228,3204191004,191,4,Kutawaringin,Sukamulya,3142,100.000000,0.000000,0.000000,0.103119,...,0.000000,0.000318,0.000318,0.000000,0.002864,0.000000,0.000000,0.011458,0.000000,0.000000
126,3204110008,110,8,Rancaekek,Sukamulya,2914,100.000000,0.000000,0.000000,0.006520,...,0.000000,0.015443,0.000000,0.000000,0.002402,0.000000,0.000000,0.015100,0.000000,0.000343
51,3204050007,50,7,Kertasari,Sukapura,2869,100.000000,0.000000,0.000000,0.003486,...,0.000000,0.004183,0.000000,0.000000,0.002440,0.000000,0.000349,0.098989,0.000000,0.000000
252,3204270006,270,6,Dayeuhkolot,Sukapura,2621,100.000000,5.723006,0.305227,0.000763,...,0.000000,0.082030,0.000382,0.000000,0.002289,0.000000,0.000000,0.018314,0.000763,0.000000
110,3204100012,100,12,Cicalengka,Tanjungwangi,2014,100.000000,0.000000,0.000000,0.016882,...,0.000000,0.005958,0.000000,0.000000,0.002979,0.000000,0.000000,0.041708,0.000000,0.000497
65,3204060013,60,13,Pacet,Tanjungwangi,2123,100.000000,0.000000,0.000000,0.011305,...,0.000000,0.008479,0.000000,0.000000,0.002355,0.000471,0.000000,0.082431,0.000000,0.000000
106,3204100008,100,8,Cicalengka,Tenjolaya,2805,100.000000,0.000000,0.713012,0.007487,...,0.000357,0.000713,0.000000,0.000000,0.004991,0.000000,0.000713,0.037433,0.001426,0.000357
14,3204020003,20,3,Pasirjambu,Tenjolaya,5448,94.254772,0.000000,0.348752,0.004772,...,0.000367,0.018539,0.000184,0.000000,0.001468,0.000367,0.000551,0.037445,0.000551,0.000367

Menampilkan semua kolom untuk baris dengan Desa duplikat:

,IDDESA,R103,R104,NAMA_KEC,Desa,total_keluarga,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15
143,3204120011,120,11,Majalaya,Bojong,6421,100.000000,0.000000,0.000000,0.036131,0.018689,0.000311,0.018377,0.000000,0.000000,0.000779,0.000000,0.000000,0.022894,0.000000,0.000156
112,3204101002,101,2,Nagreg,Bojong,2147,100.000000,0.000000,0.000000,0.050769,0.042385,0.000000,0.027946,0.000000,0.000000,0.001863,0.000000,0.000000,0.018631,0.000000,0.000000
130,3204110012,110,12,Rancaekek,Cangkuang,4712,100.000000,0.000000,0.000000,0.000637,0.043506,0.000000,0.009975,0.000000,0.000000,0.000637,0.000000,0.000000,0.067912,0.000212,0.000000
200,3204161006,161,6,Cangkuang,Cangkuang,3158,100.000000,7.504750,0.000000,0.045915,0.079164,0.000633,0.066498,0.000317,0.000000,0.000950,0.000317,0.000317,0.079481,0.000317,0.000317
17,3204020006,20,6,Pasirjambu,Cibodas,2929,100.000000,0.000000,0.000000,0.006145,0.032776,0.000341,0.005804,0.000000,0.000000,0.004097,0.000000,0.000000,0.020143,0.000000,0.000341
231,3204191007,191,7,Kutawaringin,Cibodas,2628,100.000000,0.000000,0.000000,0.008371,0.015221,0.000000,0.009513,0.000000,0.000000,0.001903,0.000381,0.000000,0.019026,0.000000,0.000000
146,3204121003,121,3,Solokan jeruk,Cibodas,3781,100.000000,3.464692,0.000000,0.004761,0.009257,0.000000,0.030944,0.000000,0.000000,0.003438,0.000000,0.000000,0.075112,0.000000,0.002116
152,3204130002,130,2,Ciparay,Cikoneng,2025,100.000000,0.000000,0.000000,0.025679,0.064198,0.001975,0.010864,0.000494,0.000000,0.004938,0.000000,0.000000,0.172840,0.000000,0.000000
21,3204020010,20,10,Pasirjambu,Cikoneng,2108,100.000000,0.000000,0.000000,0.120493,0.025142,0.000000,0.008065,0.000000,0.000000,0.005218,0.000000,0.000000,0.067837,0.000000,0.000000
232,3204191008,191,8,Kutawaringin,Jatisari,4024,100.000000,0.000000,0.000000,0.023111,0.037773,0.000000,0.004970,0.000000,0.000000,0.001988,0.000000,0.000249,0.013419,0.000000,0.000000
195,3204161001,161,1,Cangkuang,Jatisari,2372,100.000000,0.000000,0.000000,0.039207,0.007589,0.000422,0.017285,0.000000,0.000000,0.003794,0.000000,0.000422,0.065346,0.000000,0.000000
233,3204191009,191,9,Kutawaringin,Jelegong,5338,100.000000,0.000000,0.000000,0.002623,0.051517,0.000375,0.014238,0.000000,0.000187,0.001124,0.000187,0.000187,0.049831,0.000000,0.000187
124,3204110006,110,6,Rancaekek,Jelegong,8712,100.000000,0.000000,0.000000,0.004936,0.028122,0.000918,0.004591,0.000000,0.000000,0.002066,0.000000,0.000230,0.149219,0.000230,0.000115
240,3204250005,250,5,Margaasih,Margaasih,8469,100.000000,0.000000,0.000000,0.026095,0.008384,0.000945,0.024914,0.000000,0.000118,0.001771,0.000590,0.000354,0.030110,0.000472,0.000118
101,3204100003,100,3,Cicalengka,Margaasih,2894,100.000000,2.142364,0.000000,0.017968,0.043538,0.000000,0.005529,0.000000,0.000000,0.003110,0.000346,0.000000,0.060124,0.000000,0.000000
13,3204020002,20,2,Pasirjambu,Margamulya,2944,99.966033,0.169837,0.000000,0.012228,0.014606,0.000000,0.029891,0.000000,0.000000,0.002378,0.000000,0.000340,0.028872,0.000000,0.000000
42,3204040011,40,11,Pangalengan,Margamulya,5936,100.000000,0.000000,0.488544,0.011287,0.033693,0.000337,0.006739,0.000337,0.000000,0.001853,0.000000,0.000337,0.047507,0.000168,0.000000
62,3204060010,60,10,Pacet,Mekarjaya,2437,100.000000,0.000000,0.287238,0.038572,0.010669,0.000410,0.029955,0.000000,0.000000,0.004103,0.000000,0.000000,0.046368,0.000000,0.000000
184,3204160001,160,1,Banjaran,Mekarjaya,3551,100.000000,2.027598,0.000000,0.038581,0.025063,0.000000,0.018586,0.000000,0.000000,0.001690,0.000000,0.000000,0.070684,0.000000,0.000000
175,3204150003,150,3,Arjasari,Mekarjaya,2341,100.000000,0.000000,0.000000,0.019650,0.042717,0.000000,0.000000,0.000000,0.000000,0.002563,0.000427,0.000000,0.047843,0.000000,0.004699
92,3204090003,90,3,Cikancung,Mekarlaksana,2243,100.000000,0.000000,0.000000,0.002675,0.062416,0.000000,0.015604,0.000000,0.000000,0.002229,0.000446,0.000000,0.019171,0.000000,0.000000
163,3204130013,130,13,Ciparay,Mekarlaksana,3147,100.000000,0.000000,0.000000,0.010804,0.008580,0.000000,0.003495,0.000000,0.000000,0.003495,0.000000,0.000000,0.080394,0.000000,0.000000
23,3204030002,30,2,Cimaung,Mekarsari,2695,100.000000,0.000000,0.000000,0.016698,0.035622,0.000000,0.025232,0.000000,0.000000,0.001855,0.000000,0.000000,0.017440,0.000000,0.000000
156,3204130006,130,6,Ciparay,Mekarsari,3932,100.000000,0.508647,0.000000,0.019329,0.055951,0.000254,0.009664,0.000000,0.000000,0.003815,0.000000,0.000000,0.071719,0.000000,0.000000
16,3204020005,20,5,Pasirjambu,Mekarsari,2127,100.000000,0.000000,0.000000,0.004701,0.029619,0.000470,0.005172,0.002351,0.000000,0.002351,0.000470,0.000000,0.019276,0.000000,0.000470
63,3204060011,60,11,Pacet,Mekarsari,2488,100.000000,0.000000,0.000000,0.124598,0.014469,0.000000,0.005627,0.000000,0.000000,0.005225,0.000000,0.000000,0.069936,0.000000,0.000000
196,3204161002,161,2,Cangkuang,Nagrak,4563,100.000000,3.243480,0.000000,0.039229,0.042735,0.000438,0.031339,0.000000,0.000000,0.002630,0.000438,0.000000,0.054789,0.000000,0.000000
57,3204060005,60,5,Pacet,Nagrak,3825,100.000000,0.000000,0.000000,0.013856,0.005229,0.000000,0.022222,0.000000,0.000000,0.004183,0.000000,0.000000,0.104052,0.000000,0.000261
188,3204160005,160,5,Banjaran,Neglasari,3157,100.000000,0.633513,0.253405,0.023440,0.058600,0.000000,0.017738,0.000000,0.000000,0.001267,0.000000,0.000317,0.048464,0.000000,0.000000
133,3204120001,120,1,Majalaya,Neglasari,3258,100.000000,0.000000,0.000000,0.003069,0.017188,0.000000,0.014119,0.000000,0.000000,0.003069,0.000000,0.000000,0.095764,0.000000,0.000000
66,3204070001,70,1,Ibun,Neglasari,1665,100.000000,0.000000,0.000000,0.010210,0.042643,0.000000,0.003604,0.000000,0.000000,0.003604,0.000000,0.000000,0.036637,0.000000,0.000000
227,3204191003,191,3,Kutawaringin,Padasuka,3335,100.000000,0.000000,0.000000,0.092354,0.044978,0.000300,0.008996,0.000000,0.000000,0.000900,0.000000,0.000300,0.004498,0.000000,0.000300
272,3204310002,310,2,Cimenyan,Padasuka,6963,100.000000,0.818613,0.000000,0.006032,0.006750,0.000431,0.015798,0.000000,0.000000,0.002154,0.000000,0.000287,0.018814,0.000000,0.000000
60,3204060008,60,8,Pacet,Pangauban,3922,100.000000,0.000000,0.000000,0.007394,0.003825,0.000000,0.009434,0.000000,0.000000,0.004080,0.000000,0.000000,0.031362,0.000000,0.000000
211,3204180007,180,7,Katapang,Pangauban,5493,100.000000,0.000000,0.182050,0.010923,0.027672,0.001820,0.046969,0.000182,0.000000,0.002913,0.000728,0.000910,0.090661,0.000728,0.000000
30,3204030009,30,9,Cimaung,Sukamaju,2814,100.000000,0.000000,0.000000,0.005686,0.041222,0.000000,0.011016,0.000000,0.000000,0.001777,0.000000,0.000355,0.008173,0.000000,0.000000
139,3204120007,120,7,Majalaya,Sukamaju,5170,100.000000,0.773694,0.000000,0.002901,0.019536,0.000193,0.037137,0.000000,0.000000,0.002708,0.000193,0.000193,0.066344,0.000193,0.000000
119,3204110001,110,1,Rancaekek,Sukamanah,2558,100.000000,0.000000,0.000000,0.011337,0.037138,0.001173,0.010164,0.000000,0.000000,0.002737,0.000000,0.000000,0.101642,0.000000,0.000782
39,3204040008,40,8,Pangalengan,Sukamanah,5673,100.000000,0.000000,0.000000,0.014983,0.030848,0.000529,0.025912,0.000705,0.000176,0.002292,0.000353,0.000176,0.037723,0.000000,0.000000
83,3204080006,80,6,Paseh,Sukamanah,3781,100.000000,0.000000,0.000000,0.017191,0.087543,0.001322,0.064004,0.000000,0.000000,0.003174,0.000264,0.000793,0.017456,0.000000,0.000000
136,3204120004,120,4,Majalaya,Sukamukti,4580,100.000000,0.000000,0.000000,0.007642,0.054585,0.000437,0.025764,0.000000,0.000000,0.001528,0.000000,0.000655,0.011572,0.000000,0.000218
214,3204180010,180,10,Katapang,Sukamukti,6114,100.000000,0.000000,0.000000,0.012594,0.016192,0.000654,0.015538,0.000000,0.000000,0.001472,0.000000,0.000000,0.030095,0.000000,0.000000
228,3204191004,191,4,Kutawaringin,Sukamulya,3142,100.000000,0.000000,0.000000,0.103119,0.074475,0.000000,0.000318,0.000318,0.000000,0.002864,0.000000,0.000000,0.011458,0.000000,0.000000
126,3204110008,110,8,Rancaekek,Sukamulya,2914,100.000000,0.000000,0.000000,0.006520,0.090940,0.000000,0.015443,0.000000,0.000000,0.002402,0.000000,0.000000,0.015100,0.000000,0.000343
51,3204050007,50,7,Kertasari,Sukapura,2869,100.000000,0.000000,0.000000,0.003486,0.013245,0.000000,0.004183,0.000000,0.000000,0.002440,0.000000,0.000349,0.098989,0.000000,0.000000
252,3204270006,270,6,Dayeuhkolot,Sukapura,2621,100.000000,5.723006,0.305227,0.000763,0.057230,0.000000,0.082030,0.000382,0.000000,0.002289,0.000000,0.000000,0.018314,0.000763,0.000000
110,3204100012,100,12,Cicalengka,Tanjungwangi,2014,100.000000,0.000000,0.000000,0.016882,0.023833,0.000000,0.005958,0.000000,0.000000,0.002979,0.000000,0.000000,0.041708,0.000000,0.000497
65,3204060013,60,13,Pacet,Tanjungwangi,2123,100.000000,0.000000,0.000000,0.011305,0.011776,0.000000,0.008479,0.000000,0.000000,0.002355,0.000471,0.000000,0.082431,0.000000,0.000000
106,3204100008,100,8,Cicalengka,Tenjolaya,2805,100.000000,0.000000,0.713012,0.007487,0.033868,0.000357,0.000713,0.000000,0.000000,0.004991,0.000000,0.000713,0.037433,0.001426,0.000357
14,3204020003,20,3,Pasirjambu,Tenjolaya,5448,94.254772,0.000000,0.348752,0.004772,0.038913,0.000367,0.018539,0.000184,0.000000,0.001468,0.000367,0.000551,0.037445,0.000551,0.000367

In [ ]:
df_podes['Desa_Kecamatan'] = df_podes['Desa'] + ' - ' + df_podes['NAMA_KEC']

print("Kolom 'Desa_Kecamatan' berhasil ditambahkan.")
display(df_podes[['Desa', 'NAMA_KEC', 'Desa_Kecamatan']].head())

Kolom 'Desa_Kecamatan' berhasil ditambahkan.

           Desa NAMA_KEC          Desa_Kecamatan
0     Panundaan  Ciwidey     Panundaan - Ciwidey
1       Ciwidey  Ciwidey       Ciwidey - Ciwidey
2    Panyocokan  Ciwidey    Panyocokan - Ciwidey
3  Lebakmuncang  Ciwidey  Lebakmuncang - Ciwidey
4      Rawabogo  Ciwidey      Rawabogo - Ciwidey

In [ ]:
df_rt['Desa'] = df_rt['Desa'].astype(str).str.lower().str.replace('_', ' ').str.strip()
df_rt['Kecamatan'] = df_rt['Kecamatan'].astype(str).str.lower().str.replace('_', ' ').str.strip()
df_rt['Desa_Kecamatan'] = df_rt['Desa'] + ' - ' + df_rt['Kecamatan']

print("Kolom 'Desa_Kecamatan' berhasil ditambahkan ke df_rt setelah standardisasi.")
display(df_rt[['Desa', 'Kecamatan', 'Desa_Kecamatan']].head())

Kolom 'Desa_Kecamatan' berhasil ditambahkan ke df_rt setelah standardisasi.

                    Desa     Kecamatan                        Desa_Kecamatan
0         cileunyi kulon      cileunyi             cileunyi kulon - cileunyi
1  jatisari kutawaringin  kutawaringin  jatisari kutawaringin - kutawaringin
2         cileunyi kulon      cileunyi             cileunyi kulon - cileunyi
3         cileunyi kulon      cileunyi             cileunyi kulon - cileunyi
4              sukamenak     margahayu                 sukamenak - margahayu

In [ ]:
df_gabungan = pd.merge(df_rt, df_podes, on='Desa_Kecamatan', how='left')

print("DataFrame berhasil digabungkan. Berikut adalah beberapa baris pertama dari DataFrame gabungan:")
display(df_gabungan.head())
print("Ukuran DataFrame gabungan:", df_gabungan.shape)

DataFrame berhasil digabungkan. Berikut adalah beberapa baris pertama dari DataFrame gabungan:

,Nama Surveyor,Tanggal Survey,Nama,Jenis Kelamin,Alamat,R103_x,Kecamatan,Desa_x,RT/RW,No. Telp/HP,...,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15
0,Fajryanti Kusuma Wardani,2023-07-10,Ayi Karmini,Perempuan,Jl Ciburial Kampung Negasari,290,cileunyi,cileunyi kulon,01/20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Khairani Cahyoja Utami,2023-07-10,Anrohana,Perempuan,Gang Babakan Cipedung No. 58,191,kutawaringin,jatisari kutawaringin,01/01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fajryanti Kusuma Wardani,2023-07-10,Elis,Perempuan,Jl Neglasari 3,290,cileunyi,cileunyi kulon,01/20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fajryanti Kusuma Wardani,2023-07-10,Ghozali,NaN,Kp Neglasari,290,cileunyi,cileunyi kulon,1/20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Febrina Nurhijah,2023-07-09,Cucu Nurhayati,Perempuan,Jalan Sumintapura,260,margahayu,sukamenak,05/10,089688618697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Ukuran DataFrame gabungan: (500, 191)

In [ ]:
nan_in_iddesa = df_gabungan['Desa'].isna().sum()

print(f"Jumlah baris di df_gabungan yang memiliki NaN pada kolom 'IDDESA' (tidak ditemukan di df_podes): {nan_in_iddesa}")

KeyError: 'Desa'

In [ ]:
pip install thefuzz fuzzywuzzy[speedup]

Collecting thefuzz
  Downloading thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Collecting fuzzywuzzy[speedup]
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from thefuzz)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting python-levenshtein>=0.12 (from fuzzywuzzy[speedup])
  Downloading python_levenshtein-0.27.5-py3-none-any.whl.metadata (3.9 kB)
Collecting Levenshtein==0.27.5 (from python-levenshtein>=0.12->fuzzywuzzy[speedup])
  Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Downloading thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Downloading python_levenshtein-0.27.5-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (157 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.4/157.4 kB 8.6 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 78.8 MB/s eta 0:00:00
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy, rapidfuzz, thefuzz, Levenshtein, python-levenshtein
Successfully installed Levenshtein-0.27.5 fuzzywuzzy-0.18.0 python-levenshtein-0.27.5 rapidfuzz-3.14.6 thefuzz-0.22.1

In [ ]:
from thefuzz import fuzz
from thefuzz import process

# Membuat list unik dari Desa_Kecamatan dari df_podes untuk dicocokkan
podes_desa_kecamatan_unique = df_podes['Desa_Kecamatan'].unique().tolist()

# Fungsi untuk menemukan kecocokan fuzzy terbaik
def find_best_match(target_string, choices, threshold=80):
    if pd.isna(target_string):
        return None, 0
    # Menggunakan process.extractOne untuk efisiensi
    # target_string: string yang ingin dicocokkan
    # choices: daftar string yang akan dicocokkan
    # scorer: fungsi untuk menghitung skor kesamaan
    # score_cutoff: skor minimum agar dianggap cocok
    best_match = process.extractOne(target_string, choices, scorer=fuzz.token_sort_ratio, score_cutoff=threshold)
    if best_match:
        return best_match[0], best_match[1]
    return None, 0

# Menerapkan fungsi pencocokan fuzzy ke df_rt
# Ini mungkin memakan waktu, jadi ada baiknya mencetak progress
print("Mulai proses fuzzy matching, ini mungkin memakan waktu...")
df_rt[['Fuzzy_Matched_Desa_Kecamatan', 'Fuzzy_Score']] = df_rt['Desa_Kecamatan'].apply(lambda x: pd.Series(find_best_match(x, podes_desa_kecamatan_unique)))

print("Fuzzy matching selesai.")
display(df_rt[['Desa_Kecamatan', 'Fuzzy_Matched_Desa_Kecamatan', 'Fuzzy_Score']].head())

Mulai proses fuzzy matching, ini mungkin memakan waktu...
Fuzzy matching selesai.

,Desa_Kecamatan,Fuzzy_Matched_Desa_Kecamatan,Fuzzy_Score
0,cileunyi kulon - cileunyi,Cileunyi kulon - Cileunyi,100.0
1,jatisari kutawaringin - kutawaringin,Kutawaringin - Kutawaringin,85.0
2,cileunyi kulon - cileunyi,Cileunyi kulon - Cileunyi,100.0
3,cileunyi kulon - cileunyi,Cileunyi kulon - Cileunyi,100.0
4,sukamenak - margahayu,Sukamenak - Margahayu,100.0

In [ ]:
# Melakukan penggabungan ulang dengan hasil fuzzy matching
df_gabungan_fuzzy = pd.merge(
    df_rt,
    df_podes,
    left_on='Fuzzy_Matched_Desa_Kecamatan',
    right_on='Desa_Kecamatan',
    how='left',
    suffixes=('_rt', '_podes')
)

print("DataFrame berhasil digabungkan dengan fuzzy matching.")
display(df_gabungan_fuzzy.head())
print("Ukuran DataFrame gabungan fuzzy:", df_gabungan_fuzzy.shape)

DataFrame berhasil digabungkan dengan fuzzy matching.

,Nama Surveyor,Tanggal Survey,Nama,Jenis Kelamin,Alamat,R103_rt,Kecamatan,Desa_rt,RT/RW,No. Telp/HP,...,X7,X8,X9,X10,X11,X12,X13,X14,X15,Desa_Kecamatan_podes
0,Fajryanti Kusuma Wardani,2023-07-10,Ayi Karmini,Perempuan,Jl Ciburial Kampung Negasari,290,cileunyi,cileunyi kulon,01/20,NaN,...,0.004890,0.000136,0.0,0.002988,0.000000,0.000272,0.069682,0.000272,0.000407,Cileunyi kulon - Cileunyi
1,Khairani Cahyoja Utami,2023-07-10,Anrohana,Perempuan,Gang Babakan Cipedung No. 58,191,kutawaringin,jatisari kutawaringin,01/01,NaN,...,0.005407,0.000000,0.0,0.001802,0.000000,0.000000,0.011896,0.000360,0.000000,Kutawaringin - Kutawaringin
2,Fajryanti Kusuma Wardani,2023-07-10,Elis,Perempuan,Jl Neglasari 3,290,cileunyi,cileunyi kulon,01/20,NaN,...,0.004890,0.000136,0.0,0.002988,0.000000,0.000272,0.069682,0.000272,0.000407,Cileunyi kulon - Cileunyi
3,Fajryanti Kusuma Wardani,2023-07-10,Ghozali,NaN,Kp Neglasari,290,cileunyi,cileunyi kulon,1/20,NaN,...,0.004890,0.000136,0.0,0.002988,0.000000,0.000272,0.069682,0.000272,0.000407,Cileunyi kulon - Cileunyi
4,Febrina Nurhijah,2023-07-09,Cucu Nurhayati,Perempuan,Jalan Sumintapura,260,margahayu,sukamenak,05/10,089688618697,...,0.003094,0.000000,0.0,0.001494,0.000107,0.000640,0.011737,0.000213,0.000320,Sukamenak - Margahayu

Ukuran DataFrame gabungan fuzzy: (500, 194)

In [ ]:
# Memeriksa kembali jumlah NaN pada kolom IDDESA setelah fuzzy matching
nan_in_iddesa_fuzzy = df_gabungan_fuzzy['IDDESA'].isna().sum()

print(f"Jumlah baris di df_gabungan_fuzzy yang memiliki NaN pada kolom 'IDDESA' (tidak ditemukan di df_podes): {nan_in_iddesa_fuzzy}")

Jumlah baris di df_gabungan_fuzzy yang memiliki NaN pada kolom 'IDDESA' (tidak ditemukan di df_podes): 5

Jika jumlah NaN berkurang, berarti fuzzy matching berhasil menemukan lebih banyak kecocokan. Kita juga bisa memeriksa kolom `Fuzzy_Score` untuk memahami kualitas kecocokan.